# curl http://localhost:6800/daemonstatus.json



# curl http://localhost:6800/schedule.json -d project=masala -d spider=mspy


# curl http://localhost:6800/addversion.json -F project=masala -F version=r23 -F egg=@myproject.egg

# curl http://localhost:6800/daemonstatus.json



# curl http://localhost:6800/schedule.json -d project=masala -d spider=mspy

# curl https://masala-test.herokuapp.com/schedule.json -d project=masala -d spider=mspy

curl https://masala-test.herokuapp.com/schedule.json -d project=default -d spider=msallspy

# curl https://masala-test.herokuapp.com/schedule.json -d project=masala -d spider=msallspy

# curl https://masala-test.herokuapp.com/daemonstatus.json

# GET https://desi49.com

# POST https://masala-test.herokuapp.com/schedule.json
# {
#     "project": "masala",
#     "spider" : "mspy"
# }